# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libraryservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import os, sys

# Add path so modules can be imported across folders
sys.path.append(os.path.dirname(os.path.realpath(__file__)))

import libraryobjects_pb2 as libraryobjects__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14libraryservice.proto\x12\x07library\x1a\x14libraryobjects.proto\x1a\x1bgoogle/protobuf/empty.proto\"0\n\x11\x43reateBookRequest\x12\x1b\n\x04\x62ook\x18\x01 \x01(\x0b\x32\r.library.Book\"\x14\n\x12\x43reateBookResponse\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\".\n\x0fGetBookResponse\x12\x1b\n\x04\x62ook\x18\x01 \x01(\x0b\x32\r.library.Book2\x96\x01\n\x10InventoryService\x12\x42\n\nCreateBook\x12\x1a.library.CreateBookRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\x07GetBook\x12\x17.library.GetBookRequest\x1a\x18.library.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libraryservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=84
  _CREATEBOOKREQUEST._serialized_end=132
  _CREATEBOOKRESPONSE._serialized_start=134
  _CREATEBOOKRESPONSE._serialized_end=154
  _GETBOOKREQUEST._serialized_start=156
  _GETBOOKREQUEST._serialized_end=186
  _GETBOOKRESPONSE._serialized_start=188
  _GETBOOKRESPONSE._serialized_end=234
  _INVENTORYSERVICE._serialized_start=237
  _INVENTORYSERVICE._serialized_end=387
# @@protoc_insertion_point(module_scope)
